// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcbotbornmmlmpylkcyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjYm90Ym9ybm1tbG1weWxrY3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDk3NzYsImV4cCI6MjA2MTY4NTc3Nn0.8bhR47CvvuwjgnX2nxjALYQHlOex71fJpr_dNveFJaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);